language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_github robertzk/stagerunner robertzk/mungebits syberia/mungebits2
- ./travis-tool.sh install_deps
- ./travis-tool.sh install_r microbenchmark knitr arules gbm glmnet party survival
- ./travis-tool.sh install_github robertzk/Ramd
- ./travis-tool.sh install_github robertzk/statsUtils robertzk/mungebits
- ./travis-tool.sh install_github robertzk/syberiaMungebits
- "./travis-tool.sh install_github jimhester/covr"
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
    rooms:
      secure: cbhXOSd0Z5G373Ogd/kow0LdEDKhdi8OfAi072h0qdeuGf4zQqe2K3GT0VGfdhHJBkYxpmMDdF83gSvy37VOJzBg1SUfT7CpFtrsBQU/U2zK2EHRn5hTizTYc/kzneTTqU5F+PipWEeQBlEwlWYy4LB6Bz47Ik+EWXmIFH2srKg=
