language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_deps
- ./travis-tool.sh install_r microbenchmark knitr arules
- ./travis-tool.sh install_github robertzk/stagerunner robertzk/tundra
- ./travis-tool.sh install_github robertzk/statsUtils robertzk/mungebits
- ./travis-tool.sh install_github robertzk/mungebitsTransformations
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
    rooms:
      secure: adYeJa1+f7wmApndxHcGfdWRPZBIcyG/7kyecWkYbMHMjB+pNlI2IGlmz5jniH3ARfloOfJ4qMsEa/o6zrAThCG70sNS7yOjpt9jCbJQDxElSck4/MBYLpDjSIMWIvqh/1jFy7vHcTuJn8oqyPZqgfRaD1jhEs7Q2MfmBde0fWs=
